# Copyright (C) 1991-2008 Altera Corporation
# Your use of Altera Corporation's design tools, logic functions 
# and other software and tools, and its AMPP partner logic 
# functions, and any output files from any of the foregoing 
# (including device programming or simulation files), and any 
# associated documentation or information are expressly subject 
# to the terms and conditions of the Altera Program License 
# Subscription Agreement, Altera MegaCore Function License 
# Agreement, or other applicable license agreement, including, 
# without limitation, that your use is for the sole purpose of 
# programming logic devices manufactured by Altera and sold by 
# Altera or its authorized distributors.  Please refer to the 
# applicable agreement for further details.

# Quartus II Version 8.1 Build 163 10/28/2008 SJ Full Version
# File: C:\mce\cards\readout_card\readout_card\synth\readout_card_ep3se50.tcl
# Generated on: Sun Nov 16 22:35:47 2008

package require ::quartus::project

set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_odt[0]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_odt[0]
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.8-V SSTL CLASS I" -to mem_clk[0]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITHOUT CALIBRATION" -to mem_clk[0]
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.8-V SSTL CLASS I" -to mem_clk_n[0]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITHOUT CALIBRATION" -to mem_clk_n[0]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_cs_n[0]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_cs_n[0]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_cke[0]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_cke[0]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_addr[0]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_addr[0]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_addr[1]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_addr[1]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_addr[2]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_addr[2]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_addr[3]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_addr[3]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_addr[4]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_addr[4]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_addr[5]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_addr[5]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_addr[6]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_addr[6]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_addr[7]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_addr[7]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_addr[8]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_addr[8]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_addr[9]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_addr[9]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_addr[10]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_addr[10]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_addr[11]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_addr[11]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_addr[12]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_addr[12]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_ba[0]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_ba[0]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_ba[1]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_ba[1]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_ras_n
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_ras_n
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_cas_n
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_cas_n
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_we_n
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_we_n
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_dq[0]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to mem_dq[0]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_dq[1]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to mem_dq[1]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_dq[2]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to mem_dq[2]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_dq[3]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to mem_dq[3]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_dq[4]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to mem_dq[4]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_dq[5]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to mem_dq[5]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_dq[6]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to mem_dq[6]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_dq[7]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to mem_dq[7]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_dq[8]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to mem_dq[8]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_dq[9]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to mem_dq[9]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_dq[10]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to mem_dq[10]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_dq[11]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to mem_dq[11]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_dq[12]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to mem_dq[12]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_dq[13]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to mem_dq[13]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_dq[14]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to mem_dq[14]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_dq[15]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to mem_dq[15]
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.8-V SSTL CLASS I" -to mem_dqs[0]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to mem_dqs[0]
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.8-V SSTL CLASS I" -to mem_dqs[1]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to mem_dqs[1]
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.8-V SSTL CLASS I" -to mem_dqsn[0]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to mem_dqsn[0]
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.8-V SSTL CLASS I" -to mem_dqsn[1]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to mem_dqsn[1]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_dm[0]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to mem_dm[0]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_dm[1]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to mem_dm[1]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 517035168 -to mem_dq[0]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 517035168 -to mem_dq[1]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 517035168 -to mem_dq[2]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 517035168 -to mem_dq[3]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 517035168 -to mem_dq[4]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 517035168 -to mem_dq[5]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 517035168 -to mem_dq[6]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 517035168 -to mem_dq[7]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 517035168 -to mem_dq[8]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 517035168 -to mem_dq[9]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 517035168 -to mem_dq[10]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 517035168 -to mem_dq[11]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 517035168 -to mem_dq[12]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 517035168 -to mem_dq[13]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 517035168 -to mem_dq[14]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 517035168 -to mem_dq[15]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 517035168 -to mem_dqs[0]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 517035168 -to mem_dqs[1]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 517035168 -to mem_dqsn[0]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 517035168 -to mem_dqsn[1]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 517035168 -to mem_dm[0]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 517035168 -to mem_dm[1]
set_location_assignment PIN_F17 -to adc1_ovr
set_location_assignment PIN_B25 -to adc2_ovr
set_location_assignment PIN_D23 -to adc3_ovr
set_location_assignment PIN_AE7 -to adc4_ovr
set_location_assignment PIN_C12 -to adc5_ovr
set_location_assignment PIN_AB3 -to adc6_ovr
set_location_assignment PIN_R1 -to adc7_ovr
set_location_assignment PIN_E13 -to adc8_ovr
set_location_assignment PIN_B19 -to adc1_rdy
set_location_assignment PIN_H20 -to adc2_rdy
set_location_assignment PIN_D24 -to adc3_rdy
set_location_assignment PIN_AE5 -to adc4_rdy
set_location_assignment PIN_D20 -to adc5_rdy
set_location_assignment PIN_D13 -to adc6_rdy
set_location_assignment PIN_AC7 -to adc7_rdy
set_location_assignment PIN_AF5 -to adc8_rdy
set_location_assignment PIN_AE4 -to adc1_clk
set_location_assignment PIN_A22 -to adc2_clk
set_location_assignment PIN_D16 -to adc3_clk
set_location_assignment PIN_Y6 -to adc4_clk
set_location_assignment PIN_E17 -to adc5_clk
set_location_assignment PIN_C19 -to adc6_clk
set_location_assignment PIN_C18 -to adc7_clk
set_location_assignment PIN_G16 -to adc8_clk
set_location_assignment PIN_P25 -to dac_FB1_dat[0]
set_location_assignment PIN_D25 -to dac_FB1_dat[1]
set_location_assignment PIN_AD13 -to dac_FB1_dat[2]
set_location_assignment PIN_V24 -to dac_FB1_dat[3]
set_location_assignment PIN_W5 -to dac_FB1_dat[4]
set_location_assignment PIN_AG4 -to dac_FB1_dat[5]
set_location_assignment PIN_N24 -to dac_FB1_dat[6]
set_location_assignment PIN_Y13 -to dac_FB1_dat[7]
set_location_assignment PIN_R25 -to dac_FB1_dat[8]
set_location_assignment PIN_AH19 -to dac_FB1_dat[9]
set_location_assignment PIN_F22 -to dac_FB1_dat[10]
set_location_assignment PIN_Y14 -to dac_FB1_dat[11]
set_location_assignment PIN_AH18 -to dac_FB1_dat[12]
set_location_assignment PIN_U8 -to dac_FB1_dat[13]
set_location_assignment PIN_AE13 -to dac_FB2_dat[0]
set_location_assignment PIN_AA15 -to dac_FB2_dat[1]
set_location_assignment PIN_AB9 -to dac_FB2_dat[2]
set_location_assignment PIN_AC1 -to dac_FB2_dat[3]
set_location_assignment PIN_AG15 -to dac_FB2_dat[4]
set_location_assignment PIN_L25 -to dac_FB2_dat[5]
set_location_assignment PIN_L26 -to dac_FB2_dat[6]
set_location_assignment PIN_M28 -to dac_FB2_dat[7]
set_location_assignment PIN_W28 -to dac_FB2_dat[8]
set_location_assignment PIN_M25 -to dac_FB2_dat[9]
set_location_assignment PIN_T23 -to dac_FB2_dat[10]
set_location_assignment PIN_R26 -to dac_FB2_dat[11]
set_location_assignment PIN_M22 -to dac_FB2_dat[12]
set_location_assignment PIN_AD12 -to dac_FB2_dat[13]
set_location_assignment PIN_W27 -to dac_FB3_dat[0]
set_location_assignment PIN_G22 -to dac_FB3_dat[1]
set_location_assignment PIN_T25 -to dac_FB3_dat[2]
set_location_assignment PIN_Y4 -to dac_FB3_dat[3]
set_location_assignment PIN_E22 -to dac_FB3_dat[4]
set_location_assignment PIN_AH16 -to dac_FB3_dat[5]
set_location_assignment PIN_U6 -to dac_FB3_dat[6]
set_location_assignment PIN_AC10 -to dac_FB3_dat[7]
set_location_assignment PIN_W1 -to dac_FB3_dat[8]
set_location_assignment PIN_Y1 -to dac_FB3_dat[9]
set_location_assignment PIN_AG18 -to dac_FB3_dat[10]
set_location_assignment PIN_A27 -to dac_FB3_dat[11]
set_location_assignment PIN_T22 -to dac_FB3_dat[12]
set_location_assignment PIN_W6 -to dac_FB3_dat[13]
set_location_assignment PIN_T9 -to dac_FB4_dat[0]
set_location_assignment PIN_AC11 -to dac_FB4_dat[1]
set_location_assignment PIN_M20 -to dac_FB4_dat[2]
set_location_assignment PIN_K28 -to dac_FB4_dat[3]
set_location_assignment PIN_M21 -to dac_FB4_dat[4]
set_location_assignment PIN_R21 -to dac_FB4_dat[5]
set_location_assignment PIN_U25 -to dac_FB4_dat[6]
set_location_assignment PIN_V23 -to dac_FB4_dat[7]
set_location_assignment PIN_U23 -to dac_FB4_dat[8]
set_location_assignment PIN_E23 -to dac_FB4_dat[9]
set_location_assignment PIN_V25 -to dac_FB4_dat[10]
set_location_assignment PIN_V27 -to dac_FB4_dat[11]
set_location_assignment PIN_P19 -to dac_FB4_dat[12]
set_location_assignment PIN_M27 -to dac_FB4_dat[13]
set_location_assignment PIN_M23 -to dac_FB5_dat[0]
set_location_assignment PIN_AE18 -to dac_FB5_dat[1]
set_location_assignment PIN_P20 -to dac_FB5_dat[2]
set_location_assignment PIN_U26 -to dac_FB5_dat[3]
set_location_assignment PIN_V26 -to dac_FB5_dat[4]
set_location_assignment PIN_M24 -to dac_FB5_dat[5]
set_location_assignment PIN_T24 -to dac_FB5_dat[6]
set_location_assignment PIN_Y3 -to dac_FB5_dat[7]
set_location_assignment PIN_AE14 -to dac_FB5_dat[8]
set_location_assignment PIN_N25 -to dac_FB5_dat[9]
set_location_assignment PIN_D22 -to dac_FB5_dat[10]
set_location_assignment PIN_U4 -to dac_FB5_dat[11]
set_location_assignment PIN_L28 -to dac_FB5_dat[12]
set_location_assignment PIN_F21 -to dac_FB5_dat[13]
set_location_assignment PIN_C23 -to dac_FB6_dat[0]
set_location_assignment PIN_AF17 -to dac_FB6_dat[1]
set_location_assignment PIN_V28 -to dac_FB6_dat[2]
set_location_assignment PIN_R20 -to dac_FB6_dat[3]
set_location_assignment PIN_AF10 -to dac_FB6_dat[4]
set_location_assignment PIN_N23 -to dac_FB6_dat[5]
set_location_assignment PIN_Y2 -to dac_FB6_dat[6]
set_location_assignment PIN_AE16 -to dac_FB6_dat[7]
set_location_assignment PIN_AH12 -to dac_FB6_dat[8]
set_location_assignment PIN_T27 -to dac_FB6_dat[9]
set_location_assignment PIN_AF19 -to dac_FB6_dat[10]
set_location_assignment PIN_AF11 -to dac_FB6_dat[11]
set_location_assignment PIN_Y5 -to dac_FB6_dat[12]
set_location_assignment PIN_AH10 -to dac_FB6_dat[13]
set_location_assignment PIN_T21 -to dac_FB7_dat[0]
set_location_assignment PIN_W2 -to dac_FB7_dat[1]
set_location_assignment PIN_AG19 -to dac_FB7_dat[2]
set_location_assignment PIN_N27 -to dac_FB7_dat[3]
set_location_assignment PIN_AH14 -to dac_FB7_dat[4]
set_location_assignment PIN_N26 -to dac_FB7_dat[5]
set_location_assignment PIN_AA9 -to dac_FB7_dat[6]
set_location_assignment PIN_T4 -to dac_FB7_dat[7]
set_location_assignment PIN_N20 -to dac_FB7_dat[8]
set_location_assignment PIN_T20 -to dac_FB7_dat[9]
set_location_assignment PIN_T2 -to dac_FB7_dat[10]
set_location_assignment PIN_U3 -to dac_FB7_dat[11]
set_location_assignment PIN_M26 -to dac_FB7_dat[12]
set_location_assignment PIN_AE12 -to dac_FB7_dat[13]
set_location_assignment PIN_AE17 -to dac_FB8_dat[0]
set_location_assignment PIN_AF16 -to dac_FB8_dat[1]
set_location_assignment PIN_AB17 -to dac_FB8_dat[2]
set_location_assignment PIN_T28 -to dac_FB8_dat[3]
set_location_assignment PIN_V4 -to dac_FB8_dat[4]
set_location_assignment PIN_U9 -to dac_FB8_dat[5]
set_location_assignment PIN_AA1 -to dac_FB8_dat[6]
set_location_assignment PIN_V1 -to dac_FB8_dat[7]
set_location_assignment PIN_AH4 -to dac_FB8_dat[8]
set_location_assignment PIN_AC16 -to dac_FB8_dat[9]
set_location_assignment PIN_AB1 -to dac_FB8_dat[10]
set_location_assignment PIN_U7 -to dac_FB8_dat[11]
set_location_assignment PIN_T8 -to dac_FB8_dat[12]
set_location_assignment PIN_AB2 -to dac_FB8_dat[13]
set_location_assignment PIN_D18 -to dac_FB_clk[0]
set_location_assignment PIN_D19 -to dac_FB_clk[1]
set_location_assignment PIN_A20 -to dac_FB_clk[2]
set_location_assignment PIN_B20 -to dac_FB_clk[3]
set_location_assignment PIN_J18 -to dac_FB_clk[4]
set_location_assignment PIN_J19 -to dac_FB_clk[5]
set_location_assignment PIN_F18 -to dac_FB_clk[6]
set_location_assignment PIN_G18 -to dac_FB_clk[7]
set_location_assignment PIN_AA13 -to dac_clk[0]
set_location_assignment PIN_AH3 -to dac_clk[1]
set_location_assignment PIN_AB11 -to dac_clk[2]
set_location_assignment PIN_AD1 -to dac_clk[3]
set_location_assignment PIN_V7 -to dac_clk[4]
set_location_assignment PIN_AF8 -to dac_clk[5]
set_location_assignment PIN_AH8 -to dac_clk[6]
set_location_assignment PIN_AE2 -to dac_clk[7]
set_location_assignment PIN_AE11 -to dac_dat[0]
set_location_assignment PIN_AG6 -to dac_dat[1]
set_location_assignment PIN_Y11 -to dac_dat[2]
set_location_assignment PIN_AH13 -to dac_dat[3]
set_location_assignment PIN_V6 -to dac_dat[4]
set_location_assignment PIN_AH6 -to dac_dat[5]
set_location_assignment PIN_AA4 -to dac_dat[6]
set_location_assignment PIN_AG10 -to dac_dat[7]
set_location_assignment PIN_AH9 -to bias_dac_ncs[0]
set_location_assignment PIN_AC12 -to bias_dac_ncs[1]
set_location_assignment PIN_AH11 -to bias_dac_ncs[2]
set_location_assignment PIN_AG12 -to bias_dac_ncs[3]
set_location_assignment PIN_W3 -to bias_dac_ncs[4]
set_location_assignment PIN_AF1 -to bias_dac_ncs[5]
set_location_assignment PIN_AB13 -to bias_dac_ncs[6]
set_location_assignment PIN_AF12 -to bias_dac_ncs[7]
set_location_assignment PIN_AH5 -to offset_dac_ncs[0]
set_location_assignment PIN_AG7 -to offset_dac_ncs[1]
set_location_assignment PIN_AH2 -to offset_dac_ncs[2]
set_location_assignment PIN_AB4 -to offset_dac_ncs[3]
set_location_assignment PIN_W4 -to offset_dac_ncs[4]
set_location_assignment PIN_Y10 -to offset_dac_ncs[5]
set_location_assignment PIN_AE9 -to offset_dac_ncs[6]
set_location_assignment PIN_AH7 -to offset_dac_ncs[7]
set_location_assignment PIN_T6 -to lvds_spare
set_location_assignment PIN_AE6 -to lvds_txa
set_location_assignment PIN_C17 -to lvds_txb
set_location_assignment PIN_AA10 -to ttl_dir1
set_location_assignment PIN_AC8 -to ttl_out1
set_location_assignment PIN_D11 -to ttl_dir2
set_location_assignment PIN_AC9 -to ttl_in2
set_location_assignment PIN_F19 -to ttl_out2
set_location_assignment PIN_R10 -to ttl_dir3
set_location_assignment PIN_T1 -to ttl_in3
set_location_assignment PIN_B26 -to ttl_out3
set_location_assignment PIN_W9 -to red_led
set_location_assignment PIN_W8 -to ylw_led
set_location_assignment PIN_U5 -to grn_led
set_location_assignment PIN_A23 -to dip_sw3
set_location_assignment PIN_A26 -to dip_sw4
set_location_assignment PIN_AG3 -to wdog
set_location_assignment PIN_R9 -to smb_clk
set_location_assignment PIN_J20 -to smb_nalert
set_location_assignment PIN_A11 -to mictor[0]
set_location_assignment PIN_E16 -to mictor[1]
set_location_assignment PIN_G20 -to mictor[2]
set_location_assignment PIN_C24 -to mictor[3]
set_location_assignment PIN_AF6 -to mictor[4]
set_location_assignment PIN_AC3 -to mictor[5]
set_location_assignment PIN_A17 -to mictor[6]
set_location_assignment PIN_AD6 -to mictor[7]
set_location_assignment PIN_A18 -to mictor[8]
set_location_assignment PIN_A21 -to mictor[9]
set_location_assignment PIN_A16 -to mictor[10]
set_location_assignment PIN_A25 -to mictor[11]
set_location_assignment PIN_E20 -to mictor[12]
set_location_assignment PIN_G21 -to mictor[13]
set_location_assignment PIN_A19 -to mictor[14]
set_location_assignment PIN_D15 -to mictor[15]
set_location_assignment PIN_Y19 -to mem_addr[0]
set_location_assignment PIN_AE20 -to mem_addr[1]
set_location_assignment PIN_AF21 -to mem_addr[2]
set_location_assignment PIN_Y18 -to mem_addr[3]
set_location_assignment PIN_AE21 -to mem_addr[4]
set_location_assignment PIN_AG21 -to mem_addr[5]
set_location_assignment PIN_Y17 -to mem_addr[6]
set_location_assignment PIN_AC20 -to mem_addr[7]
set_location_assignment PIN_AE19 -to mem_addr[8]
set_location_assignment PIN_AA19 -to mem_addr[9]
set_location_assignment PIN_AA23 -to mem_addr[10]
set_location_assignment PIN_W21 -to mem_addr[11]
set_location_assignment PIN_AD28 -to mem_addr[12]
set_location_assignment PIN_AB24 -to mem_ba[0]
set_location_assignment PIN_AD27 -to mem_ba[1]
set_location_assignment PIN_AC19 -to mem_cas_n
set_location_assignment PIN_AA18 -to mem_cke[0]
set_location_assignment PIN_AF20 -to mem_cs_n[0]
set_location_assignment PIN_AF26 -to mem_dm[0]
set_location_assignment PIN_AD24 -to mem_dm[1]
set_location_assignment PIN_AD19 -to mem_odt[0]
set_location_assignment PIN_AD18 -to mem_ras_n
set_location_assignment PIN_AB19 -to mem_we_n
set_location_assignment PIN_AG16 -to pnf
set_location_assignment PIN_AG13 -to pnf_per_byte[0]
set_location_assignment PIN_AB16 -to pnf_per_byte[1]
set_location_assignment PIN_AE8 -to pnf_per_byte[2]
set_location_assignment PIN_AE15 -to pnf_per_byte[3]
set_location_assignment PIN_AD16 -to pnf_per_byte[4]
set_location_assignment PIN_AH17 -to pnf_per_byte[5]
set_location_assignment PIN_Y15 -to pnf_per_byte[6]
set_location_assignment PIN_AC17 -to pnf_per_byte[7]
set_location_assignment PIN_AG9 -to test_complete
set_location_assignment PIN_AF14 -to test_status[0]
set_location_assignment PIN_J15 -to test_status[1]
set_location_assignment PIN_AF15 -to test_status[2]
set_location_assignment PIN_AH15 -to test_status[3]
set_location_assignment PIN_C20 -to test_status[4]
set_location_assignment PIN_A12 -to test_status[5]
set_location_assignment PIN_R6 -to test_status[6]
set_location_assignment PIN_AE10 -to test_status[7]
set_location_assignment PIN_AF9 -to card_id
set_location_assignment PIN_U1 -to smb_data
set_location_assignment PIN_AE27 -to mem_clk[0]
set_location_assignment PIN_AH27 -to mem_dq[0]
set_location_assignment PIN_AH25 -to mem_dq[1]
set_location_assignment PIN_AG25 -to mem_dq[2]
set_location_assignment PIN_AG27 -to mem_dq[3]
set_location_assignment PIN_AH26 -to mem_dq[4]
set_location_assignment PIN_AB20 -to mem_dq[5]
set_location_assignment PIN_AB21 -to mem_dq[6]
set_location_assignment PIN_AD21 -to mem_dq[7]
set_location_assignment PIN_AE23 -to mem_dq[8]
set_location_assignment PIN_AF24 -to mem_dq[9]
set_location_assignment PIN_AE24 -to mem_dq[10]
set_location_assignment PIN_AF23 -to mem_dq[11]
set_location_assignment PIN_AG24 -to mem_dq[12]
set_location_assignment PIN_AH20 -to mem_dq[13]
set_location_assignment PIN_AH21 -to mem_dq[14]
set_location_assignment PIN_AH22 -to mem_dq[15]
set_location_assignment PIN_AD22 -to mem_dqs[0]
set_location_assignment PIN_AH23 -to mem_dqs[1]
set_location_assignment PIN_U2 -to inclk
set_location_assignment PIN_R27 -to rst_n
set_location_assignment PIN_D12 -to ttl_in1
set_location_assignment PIN_AE1 -to slot_id[0]
set_location_assignment PIN_AG1 -to slot_id[1]
set_location_assignment PIN_AD7 -to slot_id[2]
set_location_assignment PIN_AC2 -to slot_id[3]
set_location_assignment PIN_K7 -to adc6_dat[0]
set_location_assignment PIN_B5 -to adc8_dat[0]
set_location_assignment PIN_N5 -to adc5_dat[0]
set_location_assignment PIN_G13 -to adc2_dat[0]
set_location_assignment PIN_F10 -to adc4_dat[0]
set_location_assignment PIN_G8 -to adc1_dat[0]
set_location_assignment PIN_D8 -to adc3_dat[0]
set_location_assignment PIN_L8 -to adc7_dat[0]
set_location_assignment PIN_J3 -to adc6_dat[4]
set_location_assignment PIN_G1 -to adc6_dat[3]
set_location_assignment PIN_H1 -to adc6_dat[2]
set_location_assignment PIN_B2 -to adc6_dat[1]
set_location_assignment PIN_F8 -to adc8_dat[4]
set_location_assignment PIN_A3 -to adc8_dat[3]
set_location_assignment PIN_N9 -to adc8_dat[2]
set_location_assignment PIN_J1 -to adc8_dat[1]
set_location_assignment PIN_N4 -to adc5_dat[4]
set_location_assignment PIN_P8 -to adc5_dat[3]
set_location_assignment PIN_M3 -to adc5_dat[2]
set_location_assignment PIN_L5 -to adc5_dat[1]
set_location_assignment PIN_C14 -to adc2_dat[4]
set_location_assignment PIN_A14 -to adc2_dat[3]
set_location_assignment PIN_B14 -to adc2_dat[2]
set_location_assignment PIN_A13 -to adc2_dat[1]
set_location_assignment PIN_A10 -to adc4_dat[4]
set_location_assignment PIN_J10 -to adc4_dat[3]
set_location_assignment PIN_E10 -to adc4_dat[2]
set_location_assignment PIN_E11 -to adc4_dat[1]
set_location_assignment PIN_D5 -to adc1_dat[4]
set_location_assignment PIN_G9 -to adc1_dat[3]
set_location_assignment PIN_D6 -to adc1_dat[2]
set_location_assignment PIN_G5 -to adc1_dat[1]
set_location_assignment PIN_A6 -to adc3_dat[4]
set_location_assignment PIN_B7 -to adc3_dat[3]
set_location_assignment PIN_A9 -to adc3_dat[2]
set_location_assignment PIN_A7 -to adc3_dat[1]
set_location_assignment PIN_B4 -to adc7_dat[4]
set_location_assignment PIN_G3 -to adc7_dat[3]
set_location_assignment PIN_H5 -to adc7_dat[2]
set_location_assignment PIN_A2 -to adc7_dat[1]
set_location_assignment PIN_G2 -to adc6_dat[5]
set_location_assignment PIN_K6 -to adc8_dat[5]
set_location_assignment PIN_M4 -to adc5_dat[5]
set_location_assignment PIN_A15 -to adc2_dat[5]
set_location_assignment PIN_C9 -to adc4_dat[5]
set_location_assignment PIN_A5 -to adc1_dat[5]
set_location_assignment PIN_G4 -to adc3_dat[5]
set_location_assignment PIN_L9 -to adc7_dat[5]
set_location_assignment PIN_H2 -to adc6_dat[6]
set_location_assignment PIN_P3 -to adc8_dat[6]
set_location_assignment PIN_N1 -to adc5_dat[6]
set_location_assignment PIN_J14 -to adc2_dat[6]
set_location_assignment PIN_B10 -to adc4_dat[6]
set_location_assignment PIN_C6 -to adc1_dat[6]
set_location_assignment PIN_F9 -to adc3_dat[6]
set_location_assignment PIN_H3 -to adc7_dat[6]
set_location_assignment PIN_J4 -to adc6_dat[13]
set_location_assignment PIN_K5 -to adc6_dat[12]
set_location_assignment PIN_K8 -to adc6_dat[11]
set_location_assignment PIN_H4 -to adc6_dat[10]
set_location_assignment PIN_B1 -to adc6_dat[9]
set_location_assignment PIN_F1 -to adc6_dat[8]
set_location_assignment PIN_K4 -to adc6_dat[7]
set_location_assignment PIN_M6 -to adc8_dat[13]
set_location_assignment PIN_N8 -to adc8_dat[12]
set_location_assignment PIN_L1 -to adc8_dat[11]
set_location_assignment PIN_K2 -to adc8_dat[10]
set_location_assignment PIN_L2 -to adc8_dat[9]
set_location_assignment PIN_L6 -to adc8_dat[8]
set_location_assignment PIN_K1 -to adc8_dat[7]
set_location_assignment PIN_N2 -to adc5_dat[13]
set_location_assignment PIN_L3 -to adc5_dat[12]
set_location_assignment PIN_P4 -to adc5_dat[11]
set_location_assignment PIN_N6 -to adc5_dat[10]
set_location_assignment PIN_N7 -to adc5_dat[9]
set_location_assignment PIN_M1 -to adc5_dat[8]
set_location_assignment PIN_L4 -to adc5_dat[7]
set_location_assignment PIN_B13 -to adc2_dat[13]
set_location_assignment PIN_C15 -to adc2_dat[12]
set_location_assignment PIN_G12 -to adc2_dat[11]
set_location_assignment PIN_F12 -to adc2_dat[10]
set_location_assignment PIN_F13 -to adc2_dat[9]
set_location_assignment PIN_H14 -to adc2_dat[8]
set_location_assignment PIN_D14 -to adc2_dat[7]
set_location_assignment PIN_J11 -to adc4_dat[13]
set_location_assignment PIN_B11 -to adc4_dat[12]
set_location_assignment PIN_J12 -to adc4_dat[11]
set_location_assignment PIN_D9 -to adc4_dat[10]
set_location_assignment PIN_D1 -to adc4_dat[9]
set_location_assignment PIN_H11 -to adc4_dat[8]
set_location_assignment PIN_C10 -to adc4_dat[7]
set_location_assignment PIN_C1 -to adc1_dat[13]
set_location_assignment PIN_C3 -to adc1_dat[12]
set_location_assignment PIN_E5 -to adc1_dat[11]
set_location_assignment PIN_C5 -to adc1_dat[10]
set_location_assignment PIN_E8 -to adc1_dat[9]
set_location_assignment PIN_D7 -to adc1_dat[8]
set_location_assignment PIN_E7 -to adc1_dat[7]
set_location_assignment PIN_C8 -to adc3_dat[13]
set_location_assignment PIN_F4 -to adc3_dat[12]
set_location_assignment PIN_H10 -to adc3_dat[11]
set_location_assignment PIN_G10 -to adc3_dat[10]
set_location_assignment PIN_D10 -to adc3_dat[9]
set_location_assignment PIN_A8 -to adc3_dat[8]
set_location_assignment PIN_B8 -to adc3_dat[7]
set_location_assignment PIN_A4 -to adc7_dat[13]
set_location_assignment PIN_K9 -to adc7_dat[12]
set_location_assignment PIN_F3 -to adc7_dat[11]
set_location_assignment PIN_E1 -to adc7_dat[10]
set_location_assignment PIN_J6 -to adc7_dat[9]
set_location_assignment PIN_E2 -to adc7_dat[8]
set_location_assignment PIN_D2 -to adc7_dat[7]
set_location_assignment PIN_V3 -to lvds_sync
set_location_assignment PIN_AB7 -to lvds_cmd
set_location_assignment PIN_N21 -to ~ALTERA_DATA0~
set_location_assignment PIN_P23 -to ~ALTERA_CRC_ERROR~
set_location_assignment PIN_D27 -to termination_blk0~_rup_pad
set_location_assignment PIN_C28 -to termination_blk0~_rdn_pad
set_location_assignment PIN_U28 -to inclk_ddr
