###########################################################################
#
# Generated by : Version 10.0 Build 262 08/18/2010 Service Pack 1 SJ Full Version
#
# Project      : readout_card
# Revision     : readout_card
#
# Date         : Mon Oct 04 13:36:51 PDT 2010
#
###########################################################################
 
 
#
# ------------------------------------------
#
# Create generated clocks based on PLLs
derive_pll_clocks -create_base_clocks -use_tan_name
#
# ------------------------------------------


# Original Clock Setting Name: inclk
create_clock -period "40.000 ns" \
             -name {inclk} {inclk}
create_clock -period "40.000 ns" -name inclk_virt

# ---------------------------------------------

# ** Clock Latency
#    -------------

# ** Clock Uncertainty
#    -----------------

# ** Multicycles
#    -----------
# ** Cuts
#    ----

# ** Input/Output Delays
#    -------------------
# QSF: -name INPUT_MAX_DELAY 11.7 ns -from rc_pll:i_rc_pll|altpll:altpll_component|_clk0 -to ADC Inputs
set_input_delay -add_delay -max 11.7 -clock [get_clocks {rc_pll:i_rc_pll|altpll:altpll_component|_clk0}] [get_ports {adc1_ovr adc1_rdy adc2_ovr adc2_rdy adc3_ovr adc3_rdy adc4_ovr adc4_rdy adc5_ovr adc5_rdy adc6_ovr adc6_rdy adc7_ovr adc7_rdy adc8_ovr adc8_rdy adc1_dat[0] adc1_dat[1] adc1_dat[2] adc1_dat[3] adc1_dat[4] adc1_dat[5] adc1_dat[6] adc1_dat[7] adc1_dat[8] adc1_dat[9] adc1_dat[10] adc1_dat[11] adc1_dat[12] adc1_dat[13] adc2_dat[0] adc2_dat[1] adc2_dat[2] adc2_dat[3] adc2_dat[4] adc2_dat[5] adc2_dat[6] adc2_dat[7] adc2_dat[8] adc2_dat[9] adc2_dat[10] adc2_dat[11] adc2_dat[12] adc2_dat[13] adc3_dat[0] adc3_dat[1] adc3_dat[2] adc3_dat[3] adc3_dat[4] adc3_dat[5] adc3_dat[6] adc3_dat[7] adc3_dat[8] adc3_dat[9] adc3_dat[10] adc3_dat[11] adc3_dat[12] adc3_dat[13] adc4_dat[0] adc4_dat[1] adc4_dat[2] adc4_dat[3] adc4_dat[4] adc4_dat[5] adc4_dat[6] adc4_dat[7] adc4_dat[8] adc4_dat[9] adc4_dat[10] adc4_dat[11] adc4_dat[12] adc4_dat[13] adc5_dat[0] adc5_dat[1] adc5_dat[2] adc5_dat[3] adc5_dat[4] adc5_dat[5] adc5_dat[6] adc5_dat[7] adc5_dat[8] adc5_dat[9] adc5_dat[10] adc5_dat[11] adc5_dat[12] adc5_dat[13] adc6_dat[0] adc6_dat[1] adc6_dat[2] adc6_dat[3] adc6_dat[4] adc6_dat[5] adc6_dat[6] adc6_dat[7] adc6_dat[8] adc6_dat[9] adc6_dat[10] adc6_dat[11] adc6_dat[12] adc6_dat[13] adc7_dat[0] adc7_dat[1] adc7_dat[2] adc7_dat[3] adc7_dat[4] adc7_dat[5] adc7_dat[6] adc7_dat[7] adc7_dat[8] adc7_dat[9] adc7_dat[10] adc7_dat[11] adc7_dat[12] adc7_dat[13] adc8_dat[0] adc8_dat[1] adc8_dat[2] adc8_dat[3] adc8_dat[4] adc8_dat[5] adc8_dat[6] adc8_dat[7] adc8_dat[8] adc8_dat[9] adc8_dat[10] adc8_dat[11] adc8_dat[12] adc8_dat[13] }]

# QSF: -name INPUT_MIN_DELAY 3.7 ns -from rc_pll:i_rc_pll|altpll:altpll_component|_clk0 -to ADC Inputs
set_input_delay -add_delay -min 3.7 -clock [get_clocks {rc_pll:i_rc_pll|altpll:altpll_component|_clk0}] [get_ports {adc1_ovr adc1_rdy adc2_ovr adc2_rdy adc3_ovr adc3_rdy adc4_ovr adc4_rdy adc5_ovr adc5_rdy adc6_ovr adc6_rdy adc7_ovr adc7_rdy adc8_ovr adc8_rdy adc1_dat[0] adc1_dat[1] adc1_dat[2] adc1_dat[3] adc1_dat[4] adc1_dat[5] adc1_dat[6] adc1_dat[7] adc1_dat[8] adc1_dat[9] adc1_dat[10] adc1_dat[11] adc1_dat[12] adc1_dat[13] adc2_dat[0] adc2_dat[1] adc2_dat[2] adc2_dat[3] adc2_dat[4] adc2_dat[5] adc2_dat[6] adc2_dat[7] adc2_dat[8] adc2_dat[9] adc2_dat[10] adc2_dat[11] adc2_dat[12] adc2_dat[13] adc3_dat[0] adc3_dat[1] adc3_dat[2] adc3_dat[3] adc3_dat[4] adc3_dat[5] adc3_dat[6] adc3_dat[7] adc3_dat[8] adc3_dat[9] adc3_dat[10] adc3_dat[11] adc3_dat[12] adc3_dat[13] adc4_dat[0] adc4_dat[1] adc4_dat[2] adc4_dat[3] adc4_dat[4] adc4_dat[5] adc4_dat[6] adc4_dat[7] adc4_dat[8] adc4_dat[9] adc4_dat[10] adc4_dat[11] adc4_dat[12] adc4_dat[13] adc5_dat[0] adc5_dat[1] adc5_dat[2] adc5_dat[3] adc5_dat[4] adc5_dat[5] adc5_dat[6] adc5_dat[7] adc5_dat[8] adc5_dat[9] adc5_dat[10] adc5_dat[11] adc5_dat[12] adc5_dat[13] adc6_dat[0] adc6_dat[1] adc6_dat[2] adc6_dat[3] adc6_dat[4] adc6_dat[5] adc6_dat[6] adc6_dat[7] adc6_dat[8] adc6_dat[9] adc6_dat[10] adc6_dat[11] adc6_dat[12] adc6_dat[13] adc7_dat[0] adc7_dat[1] adc7_dat[2] adc7_dat[3] adc7_dat[4] adc7_dat[5] adc7_dat[6] adc7_dat[7] adc7_dat[8] adc7_dat[9] adc7_dat[10] adc7_dat[11] adc7_dat[12] adc7_dat[13] adc8_dat[0] adc8_dat[1] adc8_dat[2] adc8_dat[3] adc8_dat[4] adc8_dat[5] adc8_dat[6] adc8_dat[7] adc8_dat[8] adc8_dat[9] adc8_dat[10] adc8_dat[11] adc8_dat[12] adc8_dat[13] }]

# QSF: -name OUTPUT_MAX_DELAY 0 ns -from rc_pll:i_rc_pll|altpll:altpll_component|_clk0 -to ADC Outputs
set_output_delay -add_delay -max 0 -clock [get_clocks {rc_pll:i_rc_pll|altpll:altpll_component|_clk0}] [get_ports {adc1_clk adc2_clk adc3_clk adc4_clk adc5_clk adc6_clk adc7_clk adc8_clk }]

# QSF: -name OUTPUT_MIN_DELAY -3.7 ns -from rc_pll:i_rc_pll|altpll:altpll_component|_clk0 -to ADC Outputs
set_output_delay -add_delay -min -3.7 -clock [get_clocks {rc_pll:i_rc_pll|altpll:altpll_component|_clk0}] [get_ports {adc1_clk adc2_clk adc3_clk adc4_clk adc5_clk adc6_clk adc7_clk adc8_clk }]

# ** Tpd requirements
#    ----------------

# ** Setup/Hold Relationships
#    ------------------------

# ** Tsu/Th requirements
#    -------------------


# ** Tco/MinTco requirements
#    -----------------------

#
# Entity Specific Timing Assignments found in
# the Timing Analyzer Settings report panel
#


# ---------------------------------------------

