###########################################################################
#
# Generated by : Version 8.1 Build 163 10/28/2008 SJ Full Version
#
# Project      : readout_card_stratix_iii
# Revision     : readout_card_stratix_iii
#
# Date         : Tue Dec 02 10:53:32 PM W. Europe Standard Time 2008
#
###########################################################################
 
 
#
# ------------------------------------------
#
# Create generated clocks based on PLLs
derive_pll_clocks -create_base_clocks
#
# ------------------------------------------


# Original Clock Setting Name: inclk
create_clock -period "40.000 ns" \
             -name {inclk} {inclk}
# ---------------------------------------------
