###########################################################################
#
# Generated by : Version 8.1 Build 163 10/28/2008 SJ Full Version
#
# Project      : readout_card_stratix_iii
# Revision     : readout_card_stratix_iii
#
# Date         : Tue Dec 02 10:53:32 PM W. Europe Standard Time 2008
#
###########################################################################
 
#Identifies PLLs or similar resources in the design and creates generated clocks for their output clock pins. Multiple generated clocks may be created for each output clock pin if the PLL is using clock switchover, one for the inclk[0] input clock pin and one for the inclk[1] input clock pin.
derive_pll_clocks -create_base_clocks -use_tan_name

# Creates a clock object and defines its waveform in the current design
create_clock -period "40.000 ns" -name {inclk} {inclk}
create_clock -period "20.000 ns" -name {adc_fco} {adc_fco}
derive_clock_uncertainty

